version: 2.1

orbs:
  nx: nrwl/nx@1.2.0

jobs:
  checks:
    docker:
      - image: cimg/node:14.17-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - nx/set-shas
      # - run:
      #     name: Run Builds
      #     command: yarn nx affected --target=build --base=$NX_BASE --parallel
      - run:
          name: Run Unit Tests
          command: yarn test
      - run:
          name: Run Lint
          command: yarn lint

workflows:
  run-ci:
    jobs:
      - checks
